apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: a63?Hdg1D83jaB
  MYSQL_DATABASE: linux_db
  MYSQL_USER: joni
  MYSQL_PASSWORD: a63?Hdg1D83jaB
